### ISSUE TITLE
where is the report file

### ISSUE THREAD

**Issue by shaunthegeek** [tomasbjerre/violation-comments-to-gitlab-gradle-plugin#2]
violations-command-line can Export to CodeClimate JSON. https://github.com/tomasbjerre/violations-command-line

```
npx violations-command-line -cc code-climate-report.json \
 -v "CHECKSTYLE" "." ".*checkstyle/main\.xml$" "Checkstyle"
```

but Java CI have no npx, so we need a gradle plugin, I try this project, but there is no gitlab report file after build:

```
./gradlew build

ls  build/reports/checkstyle
changed-files.html main.html          test.html
changed-files.xml  main.xml           test.xml
```

how to use this plugin?

**Comment by tomasbjerre** [comment]
This plugin can create codeclimate-file:
https://github.com/tomasbjerre/violations-gradle-plugin
